# Site settings
name: 赵小白的博客
email: 15136858562@163.com
author: 赵赵赵小白
url: http://www.idearfree.com
resume_site:
github: https://github.com/zzzxb/zzzxb.github.io.git
baseurl: ""
description: I want to see the world!
meta_description: 每个人都有不堪的曾经,但未来你说了算.
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: zzzxb
highlighter: Pygments

