# Site settings
name: 赵小白的博客
email: idearfree@163.com
author: 赵赵赵小白
url: http://www.idearfree.com
resume_site:
github: https://github.com/zzzxb/zzzxb.github.io.git
baseurl: ""
description: Actually, less is more!
meta_description: 远方有多远,请你告诉我!
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。
